name: selfrenew_space
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_screenutil: ^5.6.0
  go_router: ^5.1.1
  statusbarz: ^1.0.12
  provider: ^6.0.3
  flutter_smart_dialog: ^4.6.2+1
  flutter_vibrate: ^1.3.0
  table_calendar: ^3.0.7
  flutter_slidable: ^2.0.0
  logger: ^1.1.0
  common_utils: ^2.1.0
  shared_preferences: ^2.0.15
  flutter_local_notifications: ^12.0.3
  custom_navigation_bar: ^0.8.2
  flutter_launcher_icons_maker: ^0.10.2
  flutter_native_splash: ^2.2.12
  easy_sidemenu: ^0.4.1
  side_sheet: ^1.0.3
  flex_color_scheme: ^6.0.1
  audioplayers: ^1.1.1
  extended_nested_scroll_view: ^5.1.3
  open_store: ^0.3.1
  url_launcher: ^6.1.6
  mailto: ^2.0.0
  flutter_switch: ^0.3.2
  flutter_svg: ^1.1.6
  readmore: ^2.2.0
  fl_chart: ^0.55.2
  auto_size_text_field: ^2.1.0
  smart_grid_view_nls: ^0.2.2
  sleek_circular_slider: ^2.0.1
  percent_indicator: ^4.2.2
  slide_countdown: ^0.3.4
  action_slider: ^0.6.0
  custom_pop_up_menu: ^1.2.4
  modal_bottom_sheet: ^2.1.2
  simple_text_field: ^2.1.0
  extended_tabs: ^4.0.1
  chips_choice: ^3.0.0
  statsfl: ^2.3.0
  lifecycle: ^0.6.0
#  sqflite: ^2.2.0+2
#  sqflite_common_ffi: ^2.2.0+1
  share_plus: ^6.1.0
  glassmorphism_ui: ^0.3.0
  timelines: ^0.1.0
  fluent_ui: ^4.0.3
  window_manager: ^0.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - 'assets/voice/bells.mp3'
    ## 图标
    - 'assets/icons/浴盆.svg'
    - 'assets/icons/用药.png'
    - 'assets/icons/算盘.png'
    - 'assets/icons/出差.png'
    - 'assets/icons/habit.svg'
    - 'assets/icons/focus.svg'

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_intl:
  enabled: true
flutter_icons:
  android: true
  ios: true
  macos: true
  windows: true
  image_path: "assets/appicon/ios.png"
