name: selfrenew_space
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_screenutil: ^5.6.0
  go_router: ^5.1.5
  statusbarz: ^1.0.12
  provider: ^6.0.3
  flutter_smart_dialog: ^4.7.0+1
  flutter_vibrate: ^1.3.0
  table_calendar: ^3.0.8
  flutter_slidable: ^2.0.0
  logger: ^1.1.0
  common_utils: ^2.1.0
  shared_preferences: ^2.0.15
  flutter_local_notifications: ^12.0.3
  custom_navigation_bar: ^0.8.2
  flutter_launcher_icons_maker: ^0.10.2
  flutter_native_splash: ^2.2.14
#  easy_sidemenu: ^0.4.1
#  side_sheet: ^1.0.3
  #  audioplayers: ^1.1.1
  extended_nested_scroll_view: ^5.1.3
  open_store: ^0.4.0
  url_launcher: ^6.1.6
  mailto: ^2.0.0
  flutter_switch: ^0.3.2
  flutter_svg: ^1.1.6
  readmore: ^2.2.0
  fl_chart: ^0.55.2
  auto_size_text_field: ^2.1.0
  smart_grid_view_nls: ^0.2.2
  percent_indicator: ^4.2.2
  slide_countdown: ^0.3.4
  action_slider: ^0.6.0
  modal_bottom_sheet: ^2.1.2
  extended_tabs: ^4.0.1
  flexi_chip: ^1.0.8
  statsfl: ^2.3.0
  lifecycle: ^0.6.0
  sqflite: ^2.2.0+3
  sqflite_common_ffi: ^2.2.0+1
  share_plus: ^6.2.0
  timelines: ^0.1.0
  window_manager: ^0.2.7
  rating_dialog: ^2.0.4
  expandable_page_view: ^1.0.17
  cron: ^0.5.0
  style_cron_job: ^1.0.4+2
  tab_container: ^2.0.0
  calendar_date_picker2: ^0.2.8
  time_planner: ^0.1.1
  # 周 月 天视图
  calendar_view: ^1.0.0
  reviews_slider: ^2.0.0
  wheel_slider: ^1.0.0
  flutter_onboarding_slider: ^1.0.8
  cupertino_onboarding: ^1.1.1
  pull_down_button: ^0.3.1
  flutter_lazy_listview: ^1.0.1
  lazy_load_indexed_stack: ^0.1.4
  pull_to_refresh: ^2.0.0
  sliding_up_panel2: ^3.2.2
  custom_sliding_segmented_control: ^1.7.3
  slowly_moving_widgets_field: ^1.0.28
  timeago: ^3.3.0
  in_app_purchase: ^3.0.8
  grouped_list: ^5.1.2

#  circular_clip_route: ^0.2.0+3
#  check_app_version: ^1.0.0+1
#  concentric_transition: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - 'assets/appicon/ios.png'
    - 'assets/voice/bells.mp3'
    ## 图标
    - 'assets/icons/浴盆.svg'
    - 'assets/icons/用药.png'
    - 'assets/icons/算盘.png'
    - 'assets/icons/出差.png'
    - 'assets/icons/蜡笔.svg'
    - 'assets/icons/喝水.svg'
    - 'assets/icons/读书.svg'
    - 'assets/icons/绘画.svg'
    - 'assets/icons/健身.svg'
    - 'assets/icons/start.svg'
    - 'assets/icons/check.svg'
    - 'assets/icons/delete.svg'
    - 'assets/icons/habit.svg'
    - 'assets/icons/focus.svg'
    - 'assets/splash/每日专注.svg'
    - 'assets/splash/每日习惯.svg'
    - 'assets/splash/图表.svg'
    - 'assets/icons/timer.svg'

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_intl:
  enabled: true
flutter_icons:
  android: false
  ios: false
  macos: true
  windows: true
  image_path: "assets/appicon/ios.png"
